name: Contrast Security
run-name: Contrast Security
on: pull_request

jobs:
  build: 
    permissions: 
      contents: read
      packages: write 
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: remove properties template
      run: rm $GITHUB_WORKSPACE/src/main/resources/application_example.properties 

    - name: rename config file 
      run: cp $GITHUB_WORKSPACE/src/main/resources/application.properties.j2 $GITHUB_WORKSPACE/src/main/resources/application.properties 

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn package -DskipTests

    - name: Rename Artifact 
      run: cp $GITHUB_WORKSPACE/target/Bento-0.0.1.war $GITHUB_WORKSPACE/target/ROOT.war

    - name: Verify Build Exists 
      run: cd $GITHUB_WORKSPACE/target/ && ls

    - uses: actions/upload-artifact@v3
      with:
        name: maven-build
        path: ./target/ROOT.war

  contrast: 
    needs: build
    permissions:
      actions: read 
      contents: read 
      security-events: write 
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v3 
      
      - name: Install Node 
        uses: actions/setup-node@v3
        with:
          node-version: 16 
      
      - name: Install Contrast 
        run: npm i -g @contrast/contrast-cli@latest 

      - name: Dowload Artifact 
        uses: actions/download-artifact@v3
        with:
          name: maven-build
          path: ROOT.war
      
      - name: Display structure of downloaded files
        run: ls -R

      - name: Contrast Scan Action
        uses: Contrast-Security-OSS/contrastscan-action@v2.0.3
        with:
          artifact: ROOT.war
          apiKey: ${{ secrets.CONTRAST_API_KEY }}
          orgId: ${{ secrets.CONTRAST_ORGANIZATION_ID }}
          authHeader: ${{ secrets.CONTRAST_AUTH_HEADER }}
          apiUrl: ${{ secrets.CONTRAST_API_URL }}
          severity: high
          fail: true

      # - name: Scan Artifact 
      #   env:
      #     CT_API_KEY: ${{ secrets.CONTRAST_API_KEY }}
      #     CT_AUTH_TOKEN: ${{ secrets.CONTRAST_ORGANIZATION_ID }}
      #     ORG_ID: ${{ secrets.CONTRAST_AUTH_HEADER }}
      #     URL: ${{ secrets.CONTRAST_API_URL }}
      #   run: |
      #     contrast-cli --scan ./builds/ROOT.war \
      #     --api_key $CT_API_KEY \
      #     --authorization $CT_AUTH_TOKEN \
      #     --organization_id $ORG_ID \
      #     --project_id 44f84082-c3c4-414c-9b63-a48b7d71f719/scans/6316924e-2335-45a6-8aa2-5e0c3d298039 \
      #     --host $URL \
      #     --language JAVA --wait_for_scan


