name: Contrast Security
run-name: Contrast Security
on: pull_request
jobs:
  build: 
    permissions: 
      contents: read
      packages: write 
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: remove properties template
      run: rm $GITHUB_WORKSPACE/src/main/resources/application_example.properties 
    - name: rename config file 
      run: cp $GITHUB_WORKSPACE/src/main/resources/application.properties.j2 $GITHUB_WORKSPACE/src/main/resources/application.properties 
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn package -DskipTests
    - name: Rename Artifact 
      run: cp $GITHUB_WORKSPACE/target/Bento-0.0.1.war $GITHUB_WORKSPACE/target/ROOT.war
    - uses: actions/upload-artifact@v3
      with:
        name: maven-build
        path: ./target/ROOT.war
  contrast: 
    needs: build
    permissions:
      actions: read 
      contents: read 
      security-events: write 
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v3 
      - name: Dowload Artifact 
        uses: actions/download-artifact@v3
        with:
          name: maven-build
          path: build
      - name: Contrast Scan Action
        uses: Contrast-Security-OSS/contrastscan-action@v2.0.3
        with:
          artifact: build/ROOT.war
          apiKey: ${{ secrets.CONTRAST_API_KEY }}
          orgId: ${{ secrets.CONTRAST_ORGANIZATION_ID }}
          authHeader: ${{ secrets.CONTRAST_AUTH_HEADER }}
          apiUrl: ${{ secrets.CONTRAST_API_URL }}
          projectName: ccdi-dev-ins-build
          fail: false
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

