name: Contrast Security
run-name: Contrast Security
on: pull_request

jobs:
  build: 
    permissions: 
      contents: read
      packages: write 
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: remove properties template
      run: rm $GITHUB_WORKSPACE/src/main/resources/application_example.properties 

    - name: rename config file 
      run: cp $GITHUB_WORKSPACE/src/main/resources/application.properties.j2 $GITHUB_WORKSPACE/src/main/resources/application.properties 

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn package -DskipTests

    - name: Rename Artifact 
      run: cp $GITHUB_WORKSPACE/target/Bento-0.0.1.war $GITHUB_WORKSPACE/target/ROOT.war

    - name: Verify Build Exists 
      run: cd $GITHUB_WORKSPACE/target/ && ls

    - uses: actions/upload-artifact@v3
      with:
        name: maven-build
        path: ./target/ROOT.war

  contrast: 
    permissions:
      actions: read 
      contents: read 
      security-events: write 
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v3 
      
      - name: Install Node 
        uses: actions/setup-node@v3
        with:
          node-version: 16 
      
      - name: Install Contrast 
        run: npm i -g @contrast/contrast-cli@latest 

      


  # build_and_scan:
  #   permissions:
  #     actions: read 
  #     contents: read 
  #     security-events: write 
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v3

  #   - name: remove properties template
  #     run: rm $GITHUB_WORKSPACE/src/main/resources/application_example.properties 

  #   - name: rename config file 
  #     run: cp $GITHUB_WORKSPACE/src/main/resources/application.properties.j2 $GITHUB_WORKSPACE/src/main/resources/application.properties 

  #   - name: Set up JDK 11
  #     uses: actions/setup-java@v3
  #     with:
  #       java-version: '11'
  #       distribution: 'adopt'

  #   - name: Build with Maven
  #     run: mvn package -DskipTests

  #   - name: Rename Artifact 
  #     run: cp $GITHUB_WORKSPACE/target/Bento-0.0.1.war $GITHUB_WORKSPACE/target/ROOT.war

  #   - name: Verify Build Exists 
  #     run: cd $GITHUB_WORKSPACE/target/ && ls

  #   - name: Contrast Scan Action
  #     uses: Contrast-Security-OSS/contrastscan-action@v2.0.3
  #     with:
  #       artifact: $GITHUB_WORKSPACE/target/ROOT.war
  #       apiUrl: https://fd001.contrastsecurity.com
  #       apiKey: ${{ secrets.CONTRAST_API_KEY }}
  #       orgId: ${{ secrets.CONTRAST_ORGANIZATION_ID }}
  #       authHeader: ${{ secrets.CONTRAST_AUTH_HEADER }}
  #       severity: low
  #       fail: false
  #       language: java

  #   - name: Upload SARIF file
  #     uses: github/codeql-action/upload-sarif@v2
  #     with:
  #       sarif_file: results.sarif