name: Contrast Security SCA
on:
  push:
    branches:
      - "security"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cleanup Files 
        run: |
          cp src/main/resources/application.properties.j2 src/main/resources/application.properties

      - name: Build Artifact
        run: mvn clean package -DskipTests

      - name: Prepare Artifact
        run: cp target/Bento-0.0.1.war target/ROOT.war

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ROOT.war
          path: target/ROOT.war

  dependency-tree:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository 
        uses: actions/checkout@v3 

      - name: Maven Dependency Tree 
        run: mvn dependency:tree
  
  # contrast:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3

  #     - name: Install Contrast CLI
  #       run: brew tap contrastsecurity/tap && brew install contrast

  #     - name: Contrast Audit
  #       run: |
  #         contrast audit --application-id

      

      # - name: Contrast SCA Action
      #   uses: Contrast-Security-OSS/contrast-sca-action@v1
      #   with:
      #     apiKey: ${{ secrets.CONTRAST_API_KEY }}
      #     orgId: ${{ secrets.CONTRAST_ORGANIZATION_ID }}
      #     authHeader: ${{ secrets.CONTRAST_AUTH_HEADER }}
      #     apiUrl: ${{ secrets.CONTRAST_API_URL }}
      #     filePath: mypath/to/config/files
      #     severity: medium
      #     fail: true