name: Contrast Security SCA
on:
  push:
    branches:
      - "security"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cleanup Files 
        run: |
          cp src/main/resources/application.properties.j2 src/main/resources/application.properties

      - name: Confirm Results
        run: cd src/main/resources && ls -la

      - name: build jar
        run: mvn -DskipTests package

      - name: Check directory
        run: cd target && ls -la

      # - name: Contrast SCA Action
      #   uses: Contrast-Security-OSS/contrast-sca-action@v1
      #   with:
      #     apiKey: ${{ secrets.CONTRAST_API_KEY }}
      #     orgId: ${{ secrets.CONTRAST_ORGANIZATION_ID }}
      #     authHeader: ${{ secrets.CONTRAST_AUTH_HEADER }}
      #     apiUrl: ${{ secrets.CONTRAST_API_URL }}
      #     filePath: mypath/to/config/files
      #     severity: medium
      #     fail: true