name: SCA and SAST Scans
run-name: Contrast Security 
on:
  pull_request:
    branches:
      - "dev**"
jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3
  #     - name: Set up JDK 11
  #       uses: actions/setup-java@v3
  #       with:
  #         java-version: '11'
  #         distribution: 'temurin'
  #     - name: Cleanup Files 
  #       run: |
  #         cp src/main/resources/application.properties.j2 src/main/resources/application.properties
  #     - name: Build Artifact
  #       run: mvn clean package -DskipTests
  #     - name: Prepare Artifact
  #       run: cp target/Bento-0.0.1.war target/ROOT.war
  #     - name: Upload Artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: ROOT.war
  #         path: target/ROOT.war

  Contrast-SCA:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Contrast CLI
        run: brew tap contrastsecurity/tap && brew install contrast
      - name: Contrast Auth
        run: |
          contrast auth \
          --api-key ${{ secrets.CONTRAST_API_KEY }} \
          --authorization ${{ secrets.CONTRAST_AUTH_HEADER }} \
          --host ${{ secrets.CONTRAST_API_URL }} \
          --organization-id ${{ secrets.CONTRAST_ORGANIZATION_ID }}
      - name: Check Working Directory
        run: ls -la
      - name: Help 
        run: contrast audit -h
      - name: Contrast Audit
        id: audit
        run: |
          contrast audit \
          --file pom.xml \
          --application-name CCDI_INS \
          --app-groups ${{ secrets.CONTRAST_APP_GROUPS }}
