name: Codacy Security Scan

on:
  pull_request:
    branches: [ "dev**", "qa**", "main"]
  push:
    branches: [ "main" ]

jobs:
  SAST:
    name: Build and Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Remove Example Properties File 
        run: rm src/main/resources/application_example.properties 
      - name: Rename Properties File 
        run: mv src/main/resources/application.properties.j2 src/main/resources/application.properties
      - name: Build SprintBoot Application 
        run: mvn clean package -DskipTests=true 
      - name: Rename WAR Artifact 
        run: mv ./target/Bento-0.0.1.war ./target/ROOT.war 
      - name: Scan with SpotBugs (via Codacy)
        uses: codacy/codacy-analysis-cli-action@master
        with:
          tool: spotbugs
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
          max-allowed-issues: 2147483647
          verbose: true
          allow-network: true 
          skip-uncommitted-files-check: true
